name: Semantic Release

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    uses: lwitzke-lodgify/SemanticRelease.Test/.github/workflows/release.yml@main
    secrets: inherit
